from typing import Final

MINISTRY_OLIVE_OIL_GI_URL: Final[str] = (
    "https://www.minagric.gr/for-farmer-2/2012-02-02-07-52-07/ellinikaproionta/1182-elaioladaelies-2"
)

PRODUCT_CATEGORIES: Final[list[dict[str, str | None]]] = [
    {
        "parent_slug": None,
        "slug": "olive-oil",
        "name": "Olive Oil",
        "category_type": "finished_product",
    },
    {
        "parent_slug": None,
        "slug": "olives",
        "name": "Olives",
        "category_type": "finished_product",
    },
    {
        "parent_slug": None,
        "slug": "honey",
        "name": "Honey & Bee Products",
        "category_type": "finished_product",
    },
    {
        "parent_slug": None,
        "slug": "dairy",
        "name": "Dairy & Cheese",
        "category_type": "finished_product",
    },
    {
        "parent_slug": None,
        "slug": "herbs",
        "name": "Herbs & Spices",
        "category_type": "ingredient",
    },
    {
        "parent_slug": None,
        "slug": "cosmetics",
        "name": "Cosmetics & Skincare",
        "category_type": "finished_product",
    },
    {
        "parent_slug": None,
        "slug": "packaging",
        "name": "Packaging",
        "category_type": "packaging",
    },
    {
        "parent_slug": None,
        "slug": "food-ingredients",
        "name": "Food Ingredients",
        "category_type": "ingredient",
    },
    {
        "parent_slug": None,
        "slug": "wine",
        "name": "Wine & Spirits",
        "category_type": "finished_product",
    },
    {
        "parent_slug": None,
        "slug": "seafood",
        "name": "Seafood",
        "category_type": "finished_product",
    },
    {
        "parent_slug": "olive-oil",
        "slug": "extra-virgin-olive-oil",
        "name": "Extra Virgin Olive Oil",
        "category_type": "finished_product",
    },
    {
        "parent_slug": "olive-oil",
        "slug": "organic-extra-virgin-olive-oil",
        "name": "Organic Extra Virgin Olive Oil",
        "category_type": "finished_product",
    },
    {
        "parent_slug": "olive-oil",
        "slug": "private-label-olive-oil",
        "name": "Private Label Olive Oil",
        "category_type": "finished_product",
    },
]

CERTIFICATIONS: Final[list[dict[str, str | None]]] = [
    {"name": "ISO 9001", "certification_type": "quality", "issuing_body": None},
    {"name": "ISO 22000", "certification_type": "food_safety", "issuing_body": None},
    {"name": "HACCP", "certification_type": "food_safety", "issuing_body": None},
    {"name": "BRC", "certification_type": "food_safety", "issuing_body": None},
    {"name": "IFS", "certification_type": "food_safety", "issuing_body": None},
    {
        "name": "Organic EU",
        "certification_type": "organic",
        "issuing_body": "EU Organic Certification Scheme",
    },
    {"name": "DIO Organic", "certification_type": "organic", "issuing_body": "DIO"},
    {
        "name": "ELGO-DIMITRA Organic",
        "certification_type": "organic",
        "issuing_body": "ELGO-DIMITRA",
    },
    {"name": "Kosher", "certification_type": "religious", "issuing_body": None},
    {"name": "Halal", "certification_type": "religious", "issuing_body": None},
    {"name": "FSSC 22000", "certification_type": "food_safety", "issuing_body": None},
    {"name": "FDA Registration", "certification_type": "market_access", "issuing_body": "FDA"},
    {"name": "GMP", "certification_type": "quality", "issuing_body": None},
]

GREEK_REGIONS: Final[list[dict[str, str | float]]] = [
    {
        "slug": "attica",
        "name": "Attica",
        "country_code": "GR",
        "region_level": "administrative_region",
        "center_latitude": 37.9838,
        "center_longitude": 23.7275,
    },
    {
        "slug": "central-macedonia",
        "name": "Central Macedonia",
        "country_code": "GR",
        "region_level": "administrative_region",
        "center_latitude": 40.6401,
        "center_longitude": 22.9444,
    },
    {
        "slug": "western-greece",
        "name": "Western Greece",
        "country_code": "GR",
        "region_level": "administrative_region",
        "center_latitude": 38.2466,
        "center_longitude": 21.7346,
    },
    {
        "slug": "crete",
        "name": "Crete",
        "country_code": "GR",
        "region_level": "administrative_region",
        "center_latitude": 35.2401,
        "center_longitude": 24.8093,
    },
    {
        "slug": "thessaly",
        "name": "Thessaly",
        "country_code": "GR",
        "region_level": "administrative_region",
        "center_latitude": 39.6390,
        "center_longitude": 22.4191,
    },
    {
        "slug": "peloponnese",
        "name": "Peloponnese",
        "country_code": "GR",
        "region_level": "administrative_region",
        "center_latitude": 37.2894,
        "center_longitude": 22.7891,
    },
    {
        "slug": "eastern-macedonia-thrace",
        "name": "Eastern Macedonia & Thrace",
        "country_code": "GR",
        "region_level": "administrative_region",
        "center_latitude": 41.1295,
        "center_longitude": 25.4066,
    },
    {
        "slug": "epirus",
        "name": "Epirus",
        "country_code": "GR",
        "region_level": "administrative_region",
        "center_latitude": 39.6650,
        "center_longitude": 20.8537,
    },
    {
        "slug": "ionian-islands",
        "name": "Ionian Islands",
        "country_code": "GR",
        "region_level": "administrative_region",
        "center_latitude": 38.1754,
        "center_longitude": 20.5692,
    },
    {
        "slug": "south-aegean",
        "name": "South Aegean",
        "country_code": "GR",
        "region_level": "administrative_region",
        "center_latitude": 36.3932,
        "center_longitude": 25.4615,
    },
    {
        "slug": "north-aegean",
        "name": "North Aegean",
        "country_code": "GR",
        "region_level": "administrative_region",
        "center_latitude": 39.1648,
        "center_longitude": 26.2714,
    },
    {
        "slug": "central-greece",
        "name": "Central Greece",
        "country_code": "GR",
        "region_level": "administrative_region",
        "center_latitude": 38.9000,
        "center_longitude": 22.4333,
    },
    {
        "slug": "western-macedonia",
        "name": "Western Macedonia",
        "country_code": "GR",
        "region_level": "administrative_region",
        "center_latitude": 40.3000,
        "center_longitude": 21.7900,
    },
]

OLIVE_OIL_GIS: Final[list[dict[str, str | None]]] = [
    {
        "name": "Viannos Heraklion Crete",
        "designation_type": "PDO",
        "product_category": "Olive Oil",
        "source_registry": "ministry",
        "registry_url": MINISTRY_OLIVE_OIL_GI_URL,
        "specification_url": None,
    },
    {
        "name": "Lygourio Asklipiou",
        "designation_type": "PDO",
        "product_category": "Olive Oil",
        "source_registry": "ministry",
        "registry_url": MINISTRY_OLIVE_OIL_GI_URL,
        "specification_url": None,
    },
    {
        "name": "Voreios Mylopotamos Rethymnis Kritis",
        "designation_type": "PDO",
        "product_category": "Olive Oil",
        "source_registry": "ministry",
        "registry_url": MINISTRY_OLIVE_OIL_GI_URL,
        "specification_url": None,
    },
    {
        "name": "Krokees Lakonias",
        "designation_type": "PDO",
        "product_category": "Olive Oil",
        "source_registry": "ministry",
        "registry_url": MINISTRY_OLIVE_OIL_GI_URL,
        "specification_url": None,
    },
    {
        "name": "Petrina Lakonias",
        "designation_type": "PDO",
        "product_category": "Olive Oil",
        "source_registry": "ministry",
        "registry_url": MINISTRY_OLIVE_OIL_GI_URL,
        "specification_url": None,
    },
    {
        "name": "Kranidi Argolidas",
        "designation_type": "PDO",
        "product_category": "Olive Oil",
        "source_registry": "ministry",
        "registry_url": MINISTRY_OLIVE_OIL_GI_URL,
        "specification_url": None,
    },
    {
        "name": "Peza Heraklion Crete",
        "designation_type": "PDO",
        "product_category": "Olive Oil",
        "source_registry": "ministry",
        "registry_url": MINISTRY_OLIVE_OIL_GI_URL,
        "specification_url": None,
    },
    {
        "name": "Archanes Heraklion Crete",
        "designation_type": "PDO",
        "product_category": "Olive Oil",
        "source_registry": "ministry",
        "registry_url": MINISTRY_OLIVE_OIL_GI_URL,
        "specification_url": None,
    },
    {
        "name": "Lakonia",
        "designation_type": "PGI",
        "product_category": "Olive Oil",
        "source_registry": "ministry",
        "registry_url": MINISTRY_OLIVE_OIL_GI_URL,
        "specification_url": None,
    },
    {
        "name": "Chania Kritis",
        "designation_type": "PGI",
        "product_category": "Olive Oil",
        "source_registry": "ministry",
        "registry_url": MINISTRY_OLIVE_OIL_GI_URL,
        "specification_url": None,
    },
    {
        "name": "Kefalonia",
        "designation_type": "PGI",
        "product_category": "Olive Oil",
        "source_registry": "ministry",
        "registry_url": MINISTRY_OLIVE_OIL_GI_URL,
        "specification_url": None,
    },
    {
        "name": "Olympia",
        "designation_type": "PGI",
        "product_category": "Olive Oil",
        "source_registry": "ministry",
        "registry_url": MINISTRY_OLIVE_OIL_GI_URL,
        "specification_url": None,
    },
    {
        "name": "Lesvos or Mytilini",
        "designation_type": "PGI",
        "product_category": "Olive Oil",
        "source_registry": "ministry",
        "registry_url": MINISTRY_OLIVE_OIL_GI_URL,
        "specification_url": None,
    },
    {
        "name": "Preveza",
        "designation_type": "PGI",
        "product_category": "Olive Oil",
        "source_registry": "ministry",
        "registry_url": MINISTRY_OLIVE_OIL_GI_URL,
        "specification_url": None,
    },
    {
        "name": "Rhodes",
        "designation_type": "PGI",
        "product_category": "Olive Oil",
        "source_registry": "ministry",
        "registry_url": MINISTRY_OLIVE_OIL_GI_URL,
        "specification_url": None,
    },
    {
        "name": "Thasos",
        "designation_type": "PGI",
        "product_category": "Olive Oil",
        "source_registry": "ministry",
        "registry_url": MINISTRY_OLIVE_OIL_GI_URL,
        "specification_url": None,
    },
    {
        "name": "Kalamata",
        "designation_type": "PDO",
        "product_category": "Olive Oil",
        "source_registry": "ministry",
        "registry_url": MINISTRY_OLIVE_OIL_GI_URL,
        "specification_url": None,
    },
    {
        "name": "Kolymvari Chanion Kritis",
        "designation_type": "PDO",
        "product_category": "Olive Oil",
        "source_registry": "ministry",
        "registry_url": MINISTRY_OLIVE_OIL_GI_URL,
        "specification_url": None,
    },
    {
        "name": "Sitia Lasithiou Kritis",
        "designation_type": "PDO",
        "product_category": "Olive Oil",
        "source_registry": "ministry",
        "registry_url": MINISTRY_OLIVE_OIL_GI_URL,
        "specification_url": None,
    },
]
