export const CATEGORIES = [
  { id: 'olive-oil', label: 'Olive Oil', icon: '🫒', count: 48 },
  { id: 'honey', label: 'Honey & Bee Products', icon: '🍯', count: 35 },
  { id: 'dairy', label: 'Dairy & Cheese', icon: '🧀', count: 27 },
  { id: 'herbs', label: 'Herbs & Spices', icon: '🌿', count: 31 },
  { id: 'cosmetics', label: 'Cosmetics & Skincare', icon: '✨', count: 22 },
  { id: 'packaging', label: 'Packaging', icon: '📦', count: 19 },
  { id: 'textiles', label: 'Textiles & Fabrics', icon: '🧵', count: 14 },
  { id: 'food-ingredients', label: 'Food Ingredients', icon: '🥫', count: 41 },
  { id: 'wine', label: 'Wine & Spirits', icon: '🍷', count: 23 },
  { id: 'seafood', label: 'Seafood', icon: '🐟', count: 18 },
];

export const CERTIFICATIONS = [
  'ISO 9001', 'ISO 22000', 'HACCP', 'BRC', 'IFS', 'Organic EU',
  'PDO', 'PGI', 'Kosher', 'Halal', 'FSSC 22000', 'GMP',
  'Fair Trade', 'Vegan Certified', 'Non-GMO'
];

export const REGIONS = [
  'Attica', 'Central Macedonia', 'Western Greece', 'Crete',
  'Thessaly', 'Peloponnese', 'Eastern Macedonia & Thrace',
  'Epirus', 'Ionian Islands', 'South Aegean', 'North Aegean',
  'Central Greece', 'Western Macedonia'
];

export const SUPPLIERS = [
  {
    id: 's1',
    name: 'Athenian Olive Co.',
    slug: 'athenian-olive-co',
    city: 'Athens',
    region: 'Attica',
    lat: 37.9838,
    lng: 23.7275,
    category: 'olive-oil',
    subcategory: 'Extra Virgin Olive Oil',
    rating: 4.9,
    reviewCount: 127,
    description: 'Premium extra virgin olive oil producer with over 40 years of heritage. Specializing in single-origin, cold-pressed olive oils from the Attica region.',
    shortDescription: 'Premium EVOO from Attica groves since 1982',
    certifications: ['ISO 22000', 'Organic EU', 'PDO', 'HACCP'],
    moq: '500 liters',
    capacity: '200,000 liters/year',
    leadTime: '2-3 weeks',
    exportReady: true,
    privateLabel: true,
    organic: true,
    sustainable: true,
    verified: true,
    responseRate: 98,
    responseTime: '< 4 hours',
    pricingTier: '€€€',
    sustainabilityScore: 92,
    yearFounded: 1982,
    employees: '25-50',
    exportMarkets: ['Germany', 'France', 'UK', 'USA', 'Japan'],
    products: ['Extra Virgin Olive Oil', 'Organic EVOO', 'Flavored Olive Oils', 'Olive Oil Gift Sets'],
    packagingOptions: ['Glass bottles', 'Tin cans', 'Bag-in-box', 'Bulk tanker'],
    gallery: [
      'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=600',
      'https://images.unsplash.com/photo-1509621064530-f7a4a6a3e069?w=600',
      'https://images.unsplash.com/photo-1510186760950-5f17e436600d?w=600',
    ],
    logo: 'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=100',
    heroImage: 'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=800',
  },
  {
    id: 's2',
    name: 'Northern Harvest Foods',
    slug: 'northern-harvest-foods',
    city: 'Thessaloniki',
    region: 'Central Macedonia',
    lat: 40.6401,
    lng: 22.9444,
    category: 'honey',
    subcategory: 'Raw Honey',
    rating: 4.7,
    reviewCount: 89,
    description: 'Family-run apiary and honey processing facility in the heart of Central Macedonia. Known for exceptional thyme and wildflower honey varieties.',
    shortDescription: 'Artisan honey producers from Northern Greece',
    certifications: ['ISO 9001', 'Organic EU', 'HACCP', 'BRC'],
    moq: '200 kg',
    capacity: '80,000 kg/year',
    leadTime: '1-2 weeks',
    exportReady: true,
    privateLabel: true,
    organic: true,
    sustainable: true,
    verified: true,
    responseRate: 95,
    responseTime: '< 6 hours',
    pricingTier: '€€',
    sustainabilityScore: 88,
    yearFounded: 1995,
    employees: '10-25',
    exportMarkets: ['Germany', 'Netherlands', 'UK', 'Sweden'],
    products: ['Thyme Honey', 'Wildflower Honey', 'Pine Honey', 'Honeycomb', 'Royal Jelly'],
    packagingOptions: ['Glass jars', 'Squeeze bottles', 'Bulk drums'],
    gallery: [
      'https://images.unsplash.com/photo-1587049352846-4a222e784d38?w=600',
      'https://images.unsplash.com/photo-1558642452-9d2a7deb7f62?w=600',
      'https://images.unsplash.com/photo-1471943311424-646960669fbc?w=600',
    ],
    logo: 'https://images.unsplash.com/photo-1587049352846-4a222e784d38?w=100',
    heroImage: 'https://images.unsplash.com/photo-1587049352846-4a222e784d38?w=800',
  },
  {
    id: 's3',
    name: 'Peloponnese Gold Oils',
    slug: 'peloponnese-gold-oils',
    city: 'Kalamata',
    region: 'Peloponnese',
    lat: 37.0388,
    lng: 22.1142,
    category: 'olive-oil',
    subcategory: 'Kalamata Olive Oil',
    rating: 4.8,
    reviewCount: 103,
    description: 'Renowned Kalamata olive oil producer offering PDO-certified oils from century-old groves. Experts in premium private-label production.',
    shortDescription: 'PDO Kalamata olive oil — heritage groves, modern production',
    certifications: ['PDO', 'ISO 22000', 'BRC', 'Organic EU', 'Kosher'],
    moq: '1,000 liters',
    capacity: '500,000 liters/year',
    leadTime: '3-4 weeks',
    exportReady: true,
    privateLabel: true,
    organic: true,
    sustainable: true,
    verified: true,
    responseRate: 96,
    responseTime: '< 8 hours',
    pricingTier: '€€€',
    sustainabilityScore: 95,
    yearFounded: 1970,
    employees: '50-100',
    exportMarkets: ['USA', 'Canada', 'Japan', 'Australia', 'Germany', 'UK'],
    products: ['Kalamata EVOO', 'Koroneiki EVOO', 'Organic EVOO', 'Bulk Olive Oil'],
    packagingOptions: ['Glass bottles', 'PET bottles', 'Tin cans', 'Bag-in-box', 'Flexitanks'],
    gallery: [
      'https://images.unsplash.com/photo-1510186760950-5f17e436600d?w=600',
      'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=600',
      'https://images.unsplash.com/photo-1509621064530-f7a4a6a3e069?w=600',
    ],
    logo: 'https://images.unsplash.com/photo-1510186760950-5f17e436600d?w=100',
    heroImage: 'https://images.unsplash.com/photo-1510186760950-5f17e436600d?w=800',
  },
  {
    id: 's4',
    name: 'Cretan Botanicals',
    slug: 'cretan-botanicals',
    city: 'Heraklion',
    region: 'Crete',
    lat: 35.3387,
    lng: 25.1442,
    category: 'cosmetics',
    subcategory: 'Natural Skincare',
    rating: 4.6,
    reviewCount: 67,
    description: 'Innovative natural cosmetics manufacturer combining ancient Cretan botanical wisdom with modern formulation science. Specializing in olive-based skincare.',
    shortDescription: 'Natural cosmetics powered by Cretan botanicals',
    certifications: ['ISO 9001', 'GMP', 'Organic EU', 'Vegan Certified'],
    moq: '1,000 units',
    capacity: '500,000 units/year',
    leadTime: '4-6 weeks',
    exportReady: true,
    privateLabel: true,
    organic: true,
    sustainable: true,
    verified: true,
    responseRate: 92,
    responseTime: '< 12 hours',
    pricingTier: '€€',
    sustainabilityScore: 90,
    yearFounded: 2008,
    employees: '25-50',
    exportMarkets: ['Germany', 'France', 'Italy', 'UK', 'Scandinavia'],
    products: ['Face Creams', 'Body Oils', 'Serums', 'Lip Balms', 'Hand Creams'],
    packagingOptions: ['Glass jars', 'Airless pumps', 'Tubes', 'Dropper bottles'],
    gallery: [
      'https://images.unsplash.com/photo-1556228720-195a672e8a03?w=600',
      'https://images.unsplash.com/photo-1570194065650-d99fb4b38b17?w=600',
      'https://images.unsplash.com/photo-1608248543803-ba4f8c70ae0b?w=600',
    ],
    logo: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?w=100',
    heroImage: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?w=800',
  },
  {
    id: 's5',
    name: 'Thessaly Dairy Partners',
    slug: 'thessaly-dairy-partners',
    city: 'Larissa',
    region: 'Thessaly',
    lat: 39.6372,
    lng: 22.4202,
    category: 'dairy',
    subcategory: 'Feta & Cheese',
    rating: 4.5,
    reviewCount: 54,
    description: 'Leading dairy cooperative in Thessaly producing authentic Greek feta, yogurt, and specialty cheeses. PDO-certified feta from local pasturelands.',
    shortDescription: 'Authentic PDO feta & dairy from Thessaly plains',
    certifications: ['PDO', 'ISO 22000', 'HACCP', 'IFS', 'FSSC 22000'],
    moq: '500 kg',
    capacity: '2,000 tons/year',
    leadTime: '2-4 weeks',
    exportReady: true,
    privateLabel: true,
    organic: false,
    sustainable: true,
    verified: true,
    responseRate: 90,
    responseTime: '< 24 hours',
    pricingTier: '€€',
    sustainabilityScore: 78,
    yearFounded: 1988,
    employees: '100-250',
    exportMarkets: ['EU', 'USA', 'Middle East', 'Asia'],
    products: ['PDO Feta', 'Greek Yogurt', 'Halloumi', 'Graviera', 'Manouri'],
    packagingOptions: ['Vacuum packs', 'Brine containers', 'Retail packs', 'Bulk blocks'],
    gallery: [
      'https://images.unsplash.com/photo-1486297678162-eb2a19b0a32d?w=600',
      'https://images.unsplash.com/photo-1559561853-08451507cbe7?w=600',
      'https://images.unsplash.com/photo-1452195100486-9cc805987862?w=600',
    ],
    logo: 'https://images.unsplash.com/photo-1486297678162-eb2a19b0a32d?w=100',
    heroImage: 'https://images.unsplash.com/photo-1486297678162-eb2a19b0a32d?w=800',
  },
  {
    id: 's6',
    name: 'Ionian Pack Solutions',
    slug: 'ionian-pack-solutions',
    city: 'Patras',
    region: 'Western Greece',
    lat: 38.2466,
    lng: 21.7346,
    category: 'packaging',
    subcategory: 'Food Packaging',
    rating: 4.4,
    reviewCount: 42,
    description: 'Modern packaging manufacturer specializing in food-grade packaging solutions. Eco-friendly materials and custom design capabilities.',
    shortDescription: 'Sustainable food packaging for Greek producers',
    certifications: ['ISO 9001', 'ISO 14001', 'BRC', 'FSC'],
    moq: '5,000 units',
    capacity: '10M units/year',
    leadTime: '3-5 weeks',
    exportReady: true,
    privateLabel: false,
    organic: false,
    sustainable: true,
    verified: true,
    responseRate: 88,
    responseTime: '< 12 hours',
    pricingTier: '€',
    sustainabilityScore: 85,
    yearFounded: 2002,
    employees: '50-100',
    exportMarkets: ['Balkans', 'Italy', 'Cyprus'],
    products: ['Glass Bottles', 'Tin Cans', 'Labels', 'Cardboard Boxes', 'Flexible Pouches'],
    packagingOptions: ['Custom sizes', 'Standard formats', 'Gift packaging'],
    gallery: [
      'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=600',
      'https://images.unsplash.com/photo-1558618666-fcd25c85f82e?w=600',
    ],
    logo: 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=100',
    heroImage: 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=800',
  },
  {
    id: 's7',
    name: 'Epirus Herb Collective',
    slug: 'epirus-herb-collective',
    city: 'Ioannina',
    region: 'Epirus',
    lat: 39.6650,
    lng: 20.8537,
    category: 'herbs',
    subcategory: 'Dried Herbs',
    rating: 4.7,
    reviewCount: 76,
    description: 'Wild-harvested and cultivated herbs from the pristine mountains of Epirus. Oregano, thyme, sage, and mountain tea sourced sustainably.',
    shortDescription: 'Wild mountain herbs from Epirus highlands',
    certifications: ['Organic EU', 'ISO 22000', 'HACCP', 'Fair Trade'],
    moq: '100 kg',
    capacity: '50,000 kg/year',
    leadTime: '1-2 weeks',
    exportReady: true,
    privateLabel: true,
    organic: true,
    sustainable: true,
    verified: true,
    responseRate: 94,
    responseTime: '< 8 hours',
    pricingTier: '€€',
    sustainabilityScore: 96,
    yearFounded: 2005,
    employees: '10-25',
    exportMarkets: ['Germany', 'UK', 'USA', 'Netherlands', 'Japan'],
    products: ['Greek Oregano', 'Mountain Tea', 'Thyme', 'Sage', 'Herb Blends'],
    packagingOptions: ['Kraft bags', 'Glass jars', 'Bulk sacks', 'Tea sachets'],
    gallery: [
      'https://images.unsplash.com/photo-1515694346937-94d85e39d29e?w=600',
      'https://images.unsplash.com/photo-1509670572094-e77d15b04090?w=600',
    ],
    logo: 'https://images.unsplash.com/photo-1515694346937-94d85e39d29e?w=100',
    heroImage: 'https://images.unsplash.com/photo-1515694346937-94d85e39d29e?w=800',
  },
  {
    id: 's8',
    name: 'Aegean Seafoods',
    slug: 'aegean-seafoods',
    city: 'Kavala',
    region: 'Eastern Macedonia & Thrace',
    lat: 40.9398,
    lng: 24.4014,
    category: 'seafood',
    subcategory: 'Processed Seafood',
    rating: 4.3,
    reviewCount: 38,
    description: 'Seafood processing and export company based in Kavala. Fresh and frozen fish, shellfish, and specialty products from the Aegean Sea.',
    shortDescription: 'Aegean seafood processing & export since 1990',
    certifications: ['IFS', 'BRC', 'HACCP', 'ISO 22000', 'MSC'],
    moq: '1 ton',
    capacity: '5,000 tons/year',
    leadTime: '1-3 weeks',
    exportReady: true,
    privateLabel: true,
    organic: false,
    sustainable: true,
    verified: true,
    responseRate: 86,
    responseTime: '< 24 hours',
    pricingTier: '€€',
    sustainabilityScore: 74,
    yearFounded: 1990,
    employees: '100-250',
    exportMarkets: ['Italy', 'Spain', 'France', 'Germany'],
    products: ['Frozen Fish', 'Smoked Mackerel', 'Anchovies', 'Sardines', 'Octopus'],
    packagingOptions: ['Vacuum packs', 'IQF bags', 'Retail trays', 'Bulk boxes'],
    gallery: [
      'https://images.unsplash.com/photo-1534604973900-c43ab4c2e0ab?w=600',
      'https://images.unsplash.com/photo-1498654200943-1088dd4438ae?w=600',
    ],
    logo: 'https://images.unsplash.com/photo-1534604973900-c43ab4c2e0ab?w=100',
    heroImage: 'https://images.unsplash.com/photo-1534604973900-c43ab4c2e0ab?w=800',
  },
  {
    id: 's9',
    name: 'Volos Olive Mill',
    slug: 'volos-olive-mill',
    city: 'Volos',
    region: 'Thessaly',
    lat: 39.3666,
    lng: 22.9425,
    category: 'olive-oil',
    subcategory: 'Bulk Olive Oil',
    rating: 4.5,
    reviewCount: 61,
    description: 'Modern olive mill near Pelion producing bulk and bottled olive oils. Strong export infrastructure and competitive pricing.',
    shortDescription: 'Pelion olive oils — bulk & bottled for export',
    certifications: ['ISO 22000', 'HACCP', 'BRC'],
    moq: '2,000 liters',
    capacity: '800,000 liters/year',
    leadTime: '2-3 weeks',
    exportReady: true,
    privateLabel: true,
    organic: false,
    sustainable: true,
    verified: true,
    responseRate: 91,
    responseTime: '< 6 hours',
    pricingTier: '€',
    sustainabilityScore: 72,
    yearFounded: 1975,
    employees: '25-50',
    exportMarkets: ['Italy', 'Germany', 'USA'],
    products: ['Bulk EVOO', 'Virgin Olive Oil', 'Pomace Oil', 'Bottled EVOO'],
    packagingOptions: ['Flexitanks', 'IBC containers', 'Glass bottles', 'Tin cans'],
    gallery: [
      'https://images.unsplash.com/photo-1509621064530-f7a4a6a3e069?w=600',
    ],
    logo: 'https://images.unsplash.com/photo-1509621064530-f7a4a6a3e069?w=100',
    heroImage: 'https://images.unsplash.com/photo-1509621064530-f7a4a6a3e069?w=800',
  },
  {
    id: 's10',
    name: 'Mykonos Wine Estate',
    slug: 'mykonos-wine-estate',
    city: 'Mykonos',
    region: 'South Aegean',
    lat: 37.4467,
    lng: 25.3289,
    category: 'wine',
    subcategory: 'Boutique Wines',
    rating: 4.8,
    reviewCount: 45,
    description: 'Boutique winery producing distinctive Aegean wines from indigenous grape varieties. Limited production, high quality.',
    shortDescription: 'Boutique Aegean wines from indigenous varieties',
    certifications: ['Organic EU', 'PDO', 'Vegan Certified'],
    moq: '500 bottles',
    capacity: '50,000 bottles/year',
    leadTime: '4-6 weeks',
    exportReady: true,
    privateLabel: false,
    organic: true,
    sustainable: true,
    verified: true,
    responseRate: 82,
    responseTime: '< 48 hours',
    pricingTier: '€€€',
    sustainabilityScore: 91,
    yearFounded: 2012,
    employees: '5-10',
    exportMarkets: ['USA', 'UK', 'Germany'],
    products: ['Assyrtiko', 'Malagousia', 'Red Blend', 'Rosé'],
    packagingOptions: ['Standard bottles', 'Gift boxes', 'Cases'],
    gallery: [
      'https://images.unsplash.com/photo-1506377247377-2a5b3b417ebb?w=600',
    ],
    logo: 'https://images.unsplash.com/photo-1506377247377-2a5b3b417ebb?w=100',
    heroImage: 'https://images.unsplash.com/photo-1506377247377-2a5b3b417ebb?w=800',
  },
  {
    id: 's11',
    name: 'Macedonian Textiles',
    slug: 'macedonian-textiles',
    city: 'Thessaloniki',
    region: 'Central Macedonia',
    lat: 40.6301,
    lng: 22.9504,
    category: 'textiles',
    subcategory: 'Cotton Fabrics',
    rating: 4.3,
    reviewCount: 29,
    description: 'Vertically integrated textile manufacturer producing premium cotton fabrics and garments. Strong private label capabilities.',
    shortDescription: 'Premium cotton textiles & private label production',
    certifications: ['ISO 9001', 'OEKO-TEX', 'GOTS'],
    moq: '1,000 meters',
    capacity: '500,000 meters/year',
    leadTime: '4-8 weeks',
    exportReady: true,
    privateLabel: true,
    organic: false,
    sustainable: true,
    verified: true,
    responseRate: 85,
    responseTime: '< 24 hours',
    pricingTier: '€€',
    sustainabilityScore: 80,
    yearFounded: 1996,
    employees: '50-100',
    exportMarkets: ['Italy', 'Germany', 'UK', 'France'],
    products: ['Cotton Fabrics', 'Linen Blends', 'Towels', 'Bed Linens'],
    packagingOptions: ['Rolls', 'Folded packs', 'Custom packaging'],
    gallery: [
      'https://images.unsplash.com/photo-1558171813-4c088753af8f?w=600',
    ],
    logo: 'https://images.unsplash.com/photo-1558171813-4c088753af8f?w=100',
    heroImage: 'https://images.unsplash.com/photo-1558171813-4c088753af8f?w=800',
  },
  {
    id: 's12',
    name: 'Crete Food Ingredients',
    slug: 'crete-food-ingredients',
    city: 'Heraklion',
    region: 'Crete',
    lat: 35.3487,
    lng: 25.1342,
    category: 'food-ingredients',
    subcategory: 'Natural Extracts',
    rating: 4.6,
    reviewCount: 53,
    description: 'Food ingredient manufacturer specializing in Mediterranean extracts, concentrates, and specialty ingredients for the food industry.',
    shortDescription: 'Mediterranean food extracts & specialty ingredients',
    certifications: ['ISO 22000', 'FSSC 22000', 'HACCP', 'Non-GMO'],
    moq: '250 kg',
    capacity: '1,000 tons/year',
    leadTime: '2-4 weeks',
    exportReady: true,
    privateLabel: true,
    organic: true,
    sustainable: true,
    verified: true,
    responseRate: 93,
    responseTime: '< 8 hours',
    pricingTier: '€€',
    sustainabilityScore: 84,
    yearFounded: 2001,
    employees: '25-50',
    exportMarkets: ['EU', 'USA', 'Middle East', 'Asia'],
    products: ['Olive Leaf Extract', 'Grape Seed Extract', 'Citrus Concentrates', 'Herb Powders'],
    packagingOptions: ['Drums', 'Bags', 'IBC containers'],
    gallery: [
      'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=600',
    ],
    logo: 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=100',
    heroImage: 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=800',
  },
];

export const REVIEWS = [
  { author: 'Maria Schmidt', company: 'German Foods GmbH', rating: 5, text: 'Exceptional quality olive oil. The team was very responsive and shipping was flawless.', date: '2025-11-15' },
  { author: 'Pierre Dubois', company: 'Maison Provence', rating: 5, text: 'We have been sourcing from them for 3 years. Consistently excellent product and service.', date: '2025-10-22' },
  { author: 'James Wilson', company: 'UK Gourmet Ltd', rating: 4, text: 'Great quality honey. Packaging could be improved for retail display.', date: '2025-09-30' },
  { author: 'Yuki Tanaka', company: 'Tokyo Fine Foods', rating: 5, text: 'Outstanding organic olive oil. Our Japanese customers love the taste profile.', date: '2025-08-18' },
];